default:
  ami: ami-cfe4b2b0
  instance_type: t2.nano
  root_volume:
    size: 8
    type: gp2
    delete_on_termination: True
  security_groups:
    - default
  role: 'default_instance_role'
  key: default
